### ISSUE TITLE
Exception: CustomCentroidBondForce: Weights for group 0 add to 0

### ISSUE THREAD

**Issue by BenCree** [Gervasiolab/OpenBPMD#3]
Hi,

I'm trying to use OpenBPMD with my own system, fairly similar to your example (similar sized protein with ligand, solvated). 

However I keep getting this error : 
```

python openbpmd.py -s complex_system.gro -p complex_system.top -o ligand0_pose0 -lig_resname MOL -nreps 1

/home/c/anaconda3/envs/openbpmd/lib/python3.7/site-packages/MDAnalysis/coordinates/base.py:892: UserWarning: Reader has no dt information, set to 1.0 ps
  warnings.warn("Reader has no dt information, set to 1.0 ps")
Traceback (most recent call last):




  File "openbpmd.py", line 576, in <module>
    main(args)
  File "openbpmd.py", line 122, in main
    args.structure, args.hill_height)
  File "openbpmd.py", line 468, in produce
    properties)
  File "/home/c/anaconda3/envs/openbpmd/lib/python3.7/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/c/anaconda3/envs/openbpmd/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: CustomCentroidBondForce: Weights for group 0 add to 0
```

I saw that in the other issue, it can be caused by an incorrect ligand name, but that's not the issue here (I can select the ligand fine as MOL in MDAnalysis). 

I inserted the code to print(lig_ha_idx, anchor_atom_idx) where you suggested and this is the output:
[] [3576, 3578, 3580, 3588, 3589, 3590, 3592, 3599, 3600, 3601, 3603, 3608, 3621, 5226, 5229, 5232, 5234]

I guess my ligand isn't being found, do we know why? Maybe i'm being silly. 

I've attached the .gro/.top files.
[complex_system.zip](https://github.com/Gervasiolab/OpenBPMD/files/10460667/complex_system.zip)
Cheers,
Ben

**Comment by dlukauskis** [comment]
Odd. The code uses the _equilibrated_ structure PDB to look for anchor and ligand atoms. What does the equilibrated file look like?

**Comment by BenCree** [comment]
Oh I see, the ligand is still called MOL in the .pdb, and same issue. I didn't notice it was using the .pdb since I didn't give it as an argument.

Here's the .pdb
[complex_pdb.zip](https://github.com/Gervasiolab/OpenBPMD/files/10465181/complex_pdb.zip)

**Comment by dlukauskis** [comment]
That's very strange, because this works fine if I use that equil PDB. If I print(lig_ha_idx, anchor_atom_idx), I get:
```[31300, 31301, 31302, 31303, 31304, 31305, 31306, 31307, 31308, 31309, 31310, 31311, 31312, 31313, 31314, 31315, 31316, 31317, 31318, 31319, 31320, 31321, 31322, 31323, 31324, 31325, 31326] [3564, 3578, 3579, 3580, 3581, 3590, 3591, 3592, 3593, 3601, 3602, 3603, 3608, 3609, 3611, 5213, 5228, 5229, 5234] ```

The only thing that comes to mind right now is this might be an MDAnalysis version. How did you using the openbpmd.py script? Did you follow the conda installation?

**Comment by BenCree** [comment]
I followed the conda installation in a fresh environment, all of the complex_system.pdb/top/gro files are in the same directory.

I ran ```python openbpmd.py -s complex_system.gro -p complex_system.top -o ligand0_pose0 -lig_resname MOL -nreps 1```

and the output of conda list : 
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
biopython                 1.79             py37h540881e_2    conda-forge
blosc                     1.21.2               hafa529b_0    conda-forge
bottleneck                1.3.5            py37hda87dfa_0    conda-forge
brotli                    1.0.9                h166bdaf_8    conda-forge
brotli-bin                1.0.9                h166bdaf_8    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.07.19           h06a4308_0    anaconda
certifi                   2022.6.15        py37h06a4308_0    anaconda
cftime                    1.6.2            py37hc105733_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
curl                      7.86.0               h2283fc2_1    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.32          py37hd23a5d3_0    conda-forge
fftw3f                    3.3.4                         2    omnia
fonttools                 4.38.0           py37h540881e_0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
grand                     1.1.0                    pypi_0    pypi
griddataformats           0.7.0              pyhd8ed1ab_0    conda-forge
gsd                       2.6.0            py37hda87dfa_0    conda-forge
hdf4                      4.2.15               h9772cbc_5    conda-forge
hdf5                      1.12.2          nompi_h4df4325_100    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
jax                       0.3.25             pyhd8ed1ab_0    conda-forge
jaxlib                    0.3.25           py37h6a678d5_1  
jinja2                    3.0.3              pyhd3eb1b0_0    anaconda
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4            py37h7cecad7_0    conda-forge
krb5                      1.19.3               h08a2579_0    conda-forge
lcms2                     2.14                 h6ed2654_0    conda-forge
ld_impl_linux-64          2.39                 hcc3a1bd_1    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_8    conda-forge
libbrotlidec              1.0.9                h166bdaf_8    conda-forge
libbrotlienc              1.0.9                h166bdaf_8    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcurl                   7.86.0               h2283fc2_1    conda-forge
libdeflate                1.14                 h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnetcdf                 4.8.1           nompi_h261ec11_106    conda-forge
libnghttp2                1.47.0               hff17c54_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libssh2                   1.10.0               hf14f497_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtiff                   4.4.0                h55922b4_4    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.10.3               h7463322_0    conda-forge
libxslt                   1.1.37               h873f0b0_0    conda-forge
libzip                    1.9.2                hc929e4a_1    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
lxml                      4.9.1            py37h540881e_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markupsafe                2.1.1            py37h7f8727e_0    anaconda
matplotlib-base           3.5.3            py37hf395dca_2    conda-forge
mdanalysis                2.1.0            py37h696cff9_4    conda-forge
mdtraj                    1.9.7            py37hcc56668_2    conda-forge
mmtf-python               1.1.3              pyhd8ed1ab_0    conda-forge
mrcfile                   1.4.3              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.4            py37h7cecad7_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
netcdf4                   1.6.1           nompi_py37hb61e06c_100    conda-forge
networkx                  2.7.1              pyhd8ed1ab_0    conda-forge
nomkl                     1.0                  h5ca1d4c_0    conda-forge
numexpr                   2.8.3           py37h85a3170_100    conda-forge
numpy                     1.21.6           py37h976b520_0    conda-forge
openjpeg                  2.5.0                h7d73246_1    conda-forge
openmm                    7.4.2           py37_cuda101_rc_1    omnia
openmmtools               0.17.0                   py37_0    omnia
openssl                   3.0.7                h0b41bf4_1    conda-forge
opt_einsum                3.3.0              pyhd3eb1b0_1    anaconda
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.3.5            py37h8c16a72_0  
parmed                    3.4.3            py37hd23a5d3_2    conda-forge
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pillow                    9.2.0            py37h850a105_2    conda-forge
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pymbar                    4.0.1            py37hda87dfa_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pytables                  3.7.0            py37h7d129aa_2    conda-forge
python                    3.7.12          hf930737_100_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.7                     3_cp37m    conda-forge
pytz                      2022.6             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py37h7f8727e_1    anaconda
readline                  8.1.2                h0f457ee_0    conda-forge
scikit-learn              1.0.2            py37hf9e9bfc_0    conda-forge
scipy                     1.7.3            py37hf2a6cf1_0    conda-forge
seaborn                   0.12.1               hd8ed1ab_0    conda-forge
seaborn-base              0.12.1             pyhd8ed1ab_0    conda-forge
setuptools                65.5.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                hbd366e4_2    conda-forge
sqlite                    3.40.0               h4ff8645_0    conda-forge
statsmodels               0.13.2           py37hda87dfa_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
typing-extensions         4.4.0                hd8ed1ab_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
unicodedata2              14.0.0           py37h540881e_1    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7b6447c_0    anaconda
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge
```

**Comment by dlukauskis** [comment]
Baffling. I've tried using MDAnalysis 2.1.0 with python 3.10 and openmm 7.7.0 ( I couldn't get py3.7 to work with MDAnalysis 2.1.0) and running the same exact input files and command and it runs just fine on my end. Here's what my conda env looks like:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
biopython                 1.80                     pypi_0    pypi
blosc                     1.21.3               hafa529b_0    conda-forge
brotli                    1.0.9                h166bdaf_8    conda-forge
brotli-bin                1.0.9                h166bdaf_8    conda-forge
brotlipy                  0.7.0                    pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1                   pypi_0    pypi
cftime                    1.6.2                    pypi_0    pypi
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.7                    pypi_0    pypi
cryptography              39.0.0                   pypi_0    pypi
cudatoolkit               11.8.0              h37601d7_11    conda-forge
curl                      7.87.0               hdc1c0ab_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
fftw                      3.3.10          nompi_hf0379b8_106    conda-forge
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               hca18f0e_1    conda-forge
griddataformats           1.0.1              pyhd8ed1ab_0    conda-forge
gsd                       2.7.0                    pypi_0    pypi
hdf4                      4.2.15               h9772cbc_5    conda-forge
hdf5                      1.12.2          nompi_h4df4325_101    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
krb5                      1.20.1               h81ceb04_0    conda-forge
lcms2                     2.14                 hfd0df8a_1    conda-forge
ld_impl_linux-64          2.39                 hcc3a1bd_1    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libaec                    1.0.6                hcb278e6_1    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_8    conda-forge
libbrotlidec              1.0.9                h166bdaf_8    conda-forge
libbrotlienc              1.0.9                h166bdaf_8    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcurl                   7.87.0               hdc1c0ab_0    conda-forge
libdeflate                1.17                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libjpeg-turbo             2.1.4                h166bdaf_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnetcdf                 4.8.1           nompi_h261ec11_106    conda-forge
libnghttp2                1.51.0               hff17c54_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libssh2                   1.10.0               hf14f497_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtiff                   4.5.0                h6adf6a1_2    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.10.3               h7463322_0    conda-forge
libzip                    1.9.2                hc929e4a_1    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
matplotlib                3.6.3                    pypi_0    pypi
matplotlib-base           3.6.3           py310he60537e_0    conda-forge
mdanalysis                2.1.0                    pypi_0    pypi
mdtraj                    1.9.7                    pypi_0    pypi
mmtf-python               1.1.3              pyhd8ed1ab_0    conda-forge
mrcfile                   1.4.3              pyhd8ed1ab_0    conda-forge
msgpack                   1.0.4                    pypi_0    pypi
msgpack-python            1.0.4           py310hbf28c38_1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
netcdf4                   1.6.2                    pypi_0    pypi
networkx                  3.0                pyhd8ed1ab_0    conda-forge
nomkl                     1.0                  h5ca1d4c_0    conda-forge
numexpr                   2.8.3                    pypi_0    pypi
numpy                     1.24.1                   pypi_0    pypi
ocl-icd                   2.3.1                h7f98852_0    conda-forge
ocl-icd-system            1.0.0                         1    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openmm                    7.7.0                    pypi_0    pypi
openssl                   3.0.7                h0b41bf4_1    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pandas                    1.5.3                    pypi_0    pypi
parmed                    3.4.4                    pypi_0    pypi
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pillow                    9.4.0                    pypi_0    pypi
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pooch                     1.6.0              pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1                    pypi_0    pypi
pytables                  3.7.0           py310hb60b9b2_3    conda-forge
python                    3.10.8          h4a9ceb5_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pytz                      2022.7.1           pyhd8ed1ab_0    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.2             pyhd8ed1ab_0    conda-forge
scikit-learn              1.2.0                    pypi_0    pypi
scipy                     1.10.0                   pypi_0    pypi
seaborn                   0.12.2               hd8ed1ab_0    conda-forge
seaborn-base              0.12.2             pyhd8ed1ab_0    conda-forge
setuptools                66.1.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                hbd366e4_2    conda-forge
statsmodels               0.13.5                   pypi_0    pypi
tables                    3.7.0                    pypi_0    pypi
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
unicodedata2              15.0.0                   pypi_0    pypi
urllib3                   1.26.14            pyhd8ed1ab_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge
```

FYI, I used these conda commands:

```
conda create -n openbpmd_py310 python=3.10
conda activate openbpmd_py310
conda install -c conda-forge mdanalysis=2.1.0
conda install -c conda-forge -c omnia openmm=7.7.0
conda install -c conda-forge mdtraj
conda install -c conda-forge parmed
```

**Comment by BenCree** [comment]
After much trial and tribulation I have found the issue. I created a new directory in OpenBPMD/examples to do my runs in. Running openbpmd.py in the /examples/xxxxx directory fails. Running in the main OpenBPMD directory works, however. A week of my life I shan't be getting back!!
